services:
  db:
    image: mysql:8.4.0
    container_name: mysql840
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=superSecretPassword
      - MYSQL_USER=yuji
      - MYSQL_PASSWORD=superSecretPassword
      - MYSQL_DATABASE=coinDB
    volumes:
      - ./data:/var/lib/mysql
